/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ConversorMaiuscula */

#ifndef _Included_ConversorMaiuscula
#define _Included_ConversorMaiuscula
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ConversorMaiuscula
 * Method:    paraMaiuscula
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_ConversorMaiuscula_paraMaiuscula
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
